### ISSUE TITLE
example of how to use ?

### ISSUE THREAD

**Issue by joeblew99** [arvitaly/gopherjs-electron#2]
Any chance you can link to an example ?

**Comment by arvitaly** [comment]
https://github.com/arvitaly/gopherjs-electron/blob/master/spec/app-spec.go
Look here
`var app = electron.GetApp();`

`var w = electron.NewBrowserWindow(&map[string]interface{}{
    "title": "title2",
})`

**Comment by joeblew99** [comment]
Had another look at this today.

The built in tests dont work for me. Seems like this code is really not working even on your tests ?

```
x-MacBook-Pro:gopherjs-electron apple$ npm test

> gopherjs-electron@0.0.1 test /Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron
> gopherjs build ./scripts/test.go -o ./spec/all-spec.js && electron scripts/test.js

App threw an error during load
TypeError: $global.describe is not a function
    at Object.Describe (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6445:11)
    at /Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6557:12
    at Object.Run (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6514:8)
    at Object.$init (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6555:16)
    at $init (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6770:13)
    at $goroutine (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:1464:19)
    at $schedule (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:1521:5)
    at $go (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:1497:3)
    at Object.<anonymous> (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6783:1)
    at Object.<anonymous> (/Users/apple/workspace/go/src/github.com/arvitaly/gopherjs-electron/scripts/test.js:6786:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at loadApplicationPackage (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:294:12)
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:336:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:173:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3
```

**Comment by joeblew99** [comment]
got it working thanks in the end.
Works very well, and thanks for sharing this on github.
